# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import distro_pb2 as distro__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in distro_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SchedulerServiceStub(object):
    """-------------------------------------------------------------------
    SERVICE DEFINITIONS
    -------------------------------------------------------------------

    The Brain: Runs on the Head Node
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterWorker = channel.unary_unary(
                '/distroai.SchedulerService/RegisterWorker',
                request_serializer=distro__pb2.WorkerRegistration.SerializeToString,
                response_deserializer=distro__pb2.RegistrationResponse.FromString,
                _registered_method=True)
        self.SendHeartbeat = channel.unary_unary(
                '/distroai.SchedulerService/SendHeartbeat',
                request_serializer=distro__pb2.Heartbeat.SerializeToString,
                response_deserializer=distro__pb2.Empty.FromString,
                _registered_method=True)
        self.SubmitTask = channel.unary_unary(
                '/distroai.SchedulerService/SubmitTask',
                request_serializer=distro__pb2.TaskRequest.SerializeToString,
                response_deserializer=distro__pb2.TaskSubmissionResponse.FromString,
                _registered_method=True)
        self.GetResultLocation = channel.unary_unary(
                '/distroai.SchedulerService/GetResultLocation',
                request_serializer=distro__pb2.ResultRequest.SerializeToString,
                response_deserializer=distro__pb2.ObjectLocation.FromString,
                _registered_method=True)


class SchedulerServiceServicer(object):
    """-------------------------------------------------------------------
    SERVICE DEFINITIONS
    -------------------------------------------------------------------

    The Brain: Runs on the Head Node
    """

    def RegisterWorker(self, request, context):
        """Workers call this to join the cluster
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendHeartbeat(self, request, context):
        """Workers call this every X seconds to say "I'm alive"
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitTask(self, request, context):
        """Clients call this to submit a function to run
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetResultLocation(self, request, context):
        """Clients call this to check if a result is ready
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SchedulerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterWorker': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterWorker,
                    request_deserializer=distro__pb2.WorkerRegistration.FromString,
                    response_serializer=distro__pb2.RegistrationResponse.SerializeToString,
            ),
            'SendHeartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.SendHeartbeat,
                    request_deserializer=distro__pb2.Heartbeat.FromString,
                    response_serializer=distro__pb2.Empty.SerializeToString,
            ),
            'SubmitTask': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitTask,
                    request_deserializer=distro__pb2.TaskRequest.FromString,
                    response_serializer=distro__pb2.TaskSubmissionResponse.SerializeToString,
            ),
            'GetResultLocation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetResultLocation,
                    request_deserializer=distro__pb2.ResultRequest.FromString,
                    response_serializer=distro__pb2.ObjectLocation.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'distroai.SchedulerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('distroai.SchedulerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SchedulerService(object):
    """-------------------------------------------------------------------
    SERVICE DEFINITIONS
    -------------------------------------------------------------------

    The Brain: Runs on the Head Node
    """

    @staticmethod
    def RegisterWorker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distroai.SchedulerService/RegisterWorker',
            distro__pb2.WorkerRegistration.SerializeToString,
            distro__pb2.RegistrationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendHeartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distroai.SchedulerService/SendHeartbeat',
            distro__pb2.Heartbeat.SerializeToString,
            distro__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distroai.SchedulerService/SubmitTask',
            distro__pb2.TaskRequest.SerializeToString,
            distro__pb2.TaskSubmissionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetResultLocation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distroai.SchedulerService/GetResultLocation',
            distro__pb2.ResultRequest.SerializeToString,
            distro__pb2.ObjectLocation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class WorkerServiceStub(object):
    """The Muscle: Runs on the Worker Nodes
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecuteTask = channel.unary_unary(
                '/distroai.WorkerService/ExecuteTask',
                request_serializer=distro__pb2.TaskDefinition.SerializeToString,
                response_deserializer=distro__pb2.TaskStatus.FromString,
                _registered_method=True)
        self.GetResult = channel.unary_unary(
                '/distroai.WorkerService/GetResult',
                request_serializer=distro__pb2.ResultRequest.SerializeToString,
                response_deserializer=distro__pb2.ResultResponse.FromString,
                _registered_method=True)


class WorkerServiceServicer(object):
    """The Muscle: Runs on the Worker Nodes
    """

    def ExecuteTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetResult(self, request, context):
        """<--- NEW
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExecuteTask': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteTask,
                    request_deserializer=distro__pb2.TaskDefinition.FromString,
                    response_serializer=distro__pb2.TaskStatus.SerializeToString,
            ),
            'GetResult': grpc.unary_unary_rpc_method_handler(
                    servicer.GetResult,
                    request_deserializer=distro__pb2.ResultRequest.FromString,
                    response_serializer=distro__pb2.ResultResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'distroai.WorkerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('distroai.WorkerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WorkerService(object):
    """The Muscle: Runs on the Worker Nodes
    """

    @staticmethod
    def ExecuteTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distroai.WorkerService/ExecuteTask',
            distro__pb2.TaskDefinition.SerializeToString,
            distro__pb2.TaskStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distroai.WorkerService/GetResult',
            distro__pb2.ResultRequest.SerializeToString,
            distro__pb2.ResultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
